from PyQt5.QtWidgets import QApplication, QWidget, QHBoxLayout, QVBoxLayout, QGroupBox, QButtonGroup, QRadioButton, QPushButton, QLabel, QSpinBox
from PyQt5.QtCore import Qt
app = QApplication([])
window = QWidget()
btn_menu = QPushButton('Меню')
btn_rest = QPushButton('Відпочити')
btn_next = QPushButton('Відповісти')
rb_ans1 = QRadioButton("1")
rb_ans2 = QRadioButton("2")
rb_ans3 = QRadioButton("3")
rb_ans4 = QRadioButton("4")
RadioGroup = QButtonGroup()
RadioGroup.addButton(rb_ans1)
RadioGroup.addButton(rb_ans2)
RadioGroup.addButton(rb_ans3)
RadioGroup.addButton(rb_ans4)
lb_question = QLabel('Запитання')
lb_result = QLabel('Правильно')
lb_right_answer = QLabel('відповідь')
sp_rest = QSpinBox()
gb_question = QGroupBox('Варіанти відповідей')
rb_v1 = QVBoxLayout()
rb_v2 = QVBoxLayout()
rb_h1 = QHBoxLayout()  
rb_v1.addWidget(rb_ans1)
rb_v1.addWidget(rb_ans2)
rb_v2.addWidget(rb_ans3)
rb_v2.addWidget(rb_ans4)
rb_h1.addLayout(rb_v1)
rb_h1.addLayout(rb_v2)
gb_question.setLayout(rb_h1)

v1_main = QVBoxLayout()
v1_main.addWidget(lb_question)
v1_main.addWidget(gb_question)
v1_main.addWidget(lb_result)
v1_main.addWidget(lb_right_answer)
v1_main.addWidget(btn_menu)
v1_main.addWidget(btn_rest)
v1_main.addWidget(btn_next)
window.setLayout(v1_main)
window.resize(550, 450)
window.show()
app.exec_()